[package]
name = "toaster"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
ctrlc = "3.2.4"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread", "time"] }
winrt-notification = "0.5.1"